default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: 123456

development:
  <<: *default
  database: hellorails_development

test:
  <<: *default
  database: hellorails_test

production:
  <<: *default
  database: hellorails_production
  username: hellorails
  password: <%= ENV['HELLORAILS_DATABASE_PASSWORD'] %>



