default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: 123456

development:
  <<: *default
  database: threads_development

test:
  <<: *default
  database: threads_test




